name: Code Quality

on:
  push:
    paths:
      - '**.mjs'
      - '**.ts'
      - '**.tsx'
      - '**.json*'
  pull_request:
    paths:
      - '**.mjs'
      - '**.ts'
      - '**.tsx'
      - '**.json*'

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .