name: Type Check

on:
  push:
    paths:
      - '**.ts'
      - '**.tsx'
      - 'package.json'
      - 'bun.lock*'
      - 'tsconfig.json'
  pull_request:
    paths:
      - '**.ts'
      - '**.tsx'
      - 'package.json'
      - 'bun.lock*'
      - 'tsconfig.json'

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run type check
        run: bun run typecheck